[package]
name = "ardan_2023_05_18_live"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "login", # Play project to get started
    "variables", # Playing with variables
]