[package]
name = "login_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth = { path = "../auth" }
clap = { version = "4.2.7", features = ["derive"] }
once_cell = "1.17.1"
