[package]
name = "collector_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
shared_data = { path = "../shared_data" }
tokio = { version = "1.28.2", features = ["full"] }
